language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_script:
    - git config --global user.email "guangqiang.dev@gmail.com"
    - git config --global user.name "Eric"

before_install:
    - rvm install 2.3.1
    - gem install fastlane
    - chmod +x travis.sh
    
notifications:
  email: false
  
script:
  - ./travis.sh

branches:
  only:
    - dev
    - staging
    - production