language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_install:
    - gem install fastlane
    
notifications:
  email: false
  
script: ./travis.sh

branches:
  only:
    - dev
    - staging
    - production