import "BaseFastfile"

# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :android

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Dev Build to Crashlytics Beta"
  lane :dev do
    increment_build

    gradle(
        task: "assemble",
        flavor: "dev",
        build_type: "Release"
    )

    upload_crashlytics()

    notify_slack

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

    desc "Submit a new Stage Build to Crashlytics Beta"
    lane :staging do
      increment_build

      gradle(
          task: "assemble",
          flavor: "staging",
          build_type: "Release"
      )

      upload_crashlytics()

      notify_slack

      # sh "your_script.sh"
      # You can also use other beta testing services here
    end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_build

       gradle(
           task: "assemble",
           flavor: "production",
           build_type: "Release"
       )

       upload_crashlytics()

       notify_slack
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
